# Generated by Django 4.2.3 on 2023-07-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referenced_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
